[package]
name = "audio_stream"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
gdnative = { version = "0.11.3" }
parking_lot = "0.12"
futures-util = "0.3.31"
reqwest = { version = "0.12.9", features = ["stream", "blocking"] }
tokio = { version = "1.41.0", features = ["full"] }
sevenz-rust = "0.5"
url = "2.4.0"
thiserror = "1.0.66"
command-group = "5.0.1"
sha2 = "0.10.8"
